### ISSUE TITLE
SCX has problems resuming from standby

### ISSUE THREAD

**Issue by SaberJ2X** [sched-ext/scx#342] opened 2024-06-09 13:38 UTC
Greetings

I've been using CachyOS with a Sched-EXT kernel and using lavd on a Steam Deck (though it might apply to other systems) that doesn't happen when I disable EXT-SCHED (sudo systemctl stop scx)

not really sure what to mention but...
a thread seems to get stuck and it causes the device to turn really unresponsive to even inputs and audio de-syncs or gets garbled

the steps to reproduce this problem are...
boot into gamemode (default behavior)
go into a game
after I'm in game, I press standby
after a few minutes, resume play...
then I quit the game and try to open another game
it usually does it this quickly, but sometimes it needs a second try (standby -> resume -> change game)
and if you have onscreen performance numbers enabled you'll see a core, or multiple, stuck on 100%

I've included pictures and a log
![IMG20240607185822](https://github.com/sched-ext/scx/assets/51719706/fd62779d-d5bf-4e4f-a722-ae2afb4d6c8b)
![IMG20240607193301](https://github.com/sched-ext/scx/assets/51719706/8f208414-a274-4ca0-8147-5e9c4d2631cd)
[lavd3.log](https://github.com/user-attachments/files/15752679/lavd3.log)

**Comment by ptr1337** [comment] 2024-06-09 14:34
Same does occur, when using rusty and going into sleep.
https://paste.cachyos.org/p/4020138.log

latest 6.9 Release, NVIDIA 4070S, 7950X3D, 0.1.10 scx-release.

**Comment by xuanruiqi** [comment] 2024-06-10 10:58
Having the same error here.

**Comment by htejun** [comment] 2024-06-10 20:40
Can someone who can reproduce the problem run the following `drgn` script?

  https://github.com/sched-ext/sched_ext/blob/sched_ext/tools/sched_ext/scx_show_state.py

It will look like this:
```
# drgn os/work/tools/sched_ext/scx_show_state.py
ops           : rusty
enabled       : 1
switching_all : 1
switched_all  : 1
enable_state  : enabled (2)
bypass_depth  : 0
nr_rejected   : 0
```

**Comment by multics69** [comment] 2024-06-12 07:09
Thank you, @SaberJ2X, for reporting the problem. 

There were two issues (as least I found).

One is the kernel does not properly run ops.cpu_online() callback when resumed. This problem should be fixed by [this PR](https://github.com/sched-ext/sched_ext/pull/220). 

`scx_lavd` had one more issue. It correctly adds up the suspended time to task's runtime so after the resume, the scheduler recognize the system is extremely busy. It should be fixed by [this PR](https://github.com/sched-ext/scx/pull/349).

**Comment by multics69** [comment] 2024-06-17 04:16
The issue is closed after kernel fix and scx_lavd fix.

**Closed by multics69** 2024-06-17 04:16 UTC
